version: '3'

services:
  mq:
    image: ibmcom/mq
    container_name: mq
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      LICENSE: 'accept'
      MQ_QMGR_NAME: 'QT01'
    networks:
      - custom_network

  db2:
    image: ibmcom/db2
    container_name: db2
    privileged: true
    ports:
      - "50000:50000"
    environment:
      LICENSE: 'accept'
      DBNAME: testdb
      DB2INST1_PASSWORD: 'db2inst1'
    #    command: su - db2inst1 -c "db2start"
    networks:
      - custom_network

  wildfly:
    image: quay.io/wildfly/wildfly
    container_name: wildfly
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ../target/batch-queue-0.0.1-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/batch-queue-0.0.1-SNAPSHOT.war
      - ./logging.properties:/opt/jboss/wildfly/standalone/configuration/logging.properties
    networks:
      - custom_network
networks:
  custom_network:
    external: true