spring:
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    username: db2inst1
    url: jdbc:db2://localhost:50000/testdb
    password: db2inst1
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

springdoc:
  api-docs:
    path: /rest-ui
  swagger-ui:
    path: /rest-ui.html
#logging:
#  level:
#    root: debug

ibm:
  mq:
    password: passw0rd
    channel: DEV.ADMIN.SVRCONN
    queueManager: QT01
    connName: localhost(1414)
    user: admin

custom:
  mq:
    destination: DEV.QUEUE.1
